---
- name: Install git
  become: true
  package:
    name: git
    state: "{{ packages_state }}"

- name: Install Python 3
  become: true
  package:
    name: python3
    state: "{{ packages_state }}"