- name: Install git
  become: true
  package:
    name: git
    state: "{{ packages_state }}"

- name: Add global gitignore file
  copy:
    src: .gitignore_global
    dest: "/home/{{ ansible_user_id }}/.gitignore_global"
    mode: 0644

- name: Add git config file
  template:
    dest: "/home/{{ ansible_user_id }}/.gitconfig"
    src: .gitconfig
    mode: 0644

- name: Install Python 3
  become: true
  package:
    name: python3
    state: "{{ packages_state }}"

- name: Install neovim
  include_tasks: astronvim.yaml

- name: Install tmux config
  include_tasks: tmux.yaml
