---
- name: Emma's Linux config
  hosts: "{{ variable_host | default([]) }}"
  vars:
    packages_state: present   # switch to "latest" to update packages when possible
  roles:
    - role: base
      tags: base
    - role: work_env
      tags: work_env
    - role: terraform
      tags: terraform
    - role: docker
      tags: docker
    - role: motd
      tags: motd
    # - role: aws
    #   tags: aws
    - role: monitoring
      tags: monitoring
