---
- name: Update bash aliases
  listen: update_aliases
  blockinfile:
    marker_begin: "HANDLER BASH ALIASES - BEGIN"
    marker_end: "HANDLER BASH ALIASES - END"
    block: "{{ lookup('template', '.bash_aliases.j2') }}"
    dest: "/home/{{ ansible_user_id }}/.bash_aliases"
  tags:
    - aliases