---
- name: Restart Docker
  listen: restart_docker
  become: true
  service:
    name: docker
    state: restarted
    enabled: true

- name: Logout prompt
  listen: logout_required
  debug:
    msg: "User-related modifications applied, please log out for them to take effect."