---
- name: Check if AWS CLI already installed
  command:
    cmd: which aws
  register: which_aws
  changed_when: false
  failed_when: false

- name: Include install if not on Amazon distributions
  include_tasks: aws-cli.yml
  when: ansible_distribution != "Amazon"

