- name: Install unzip (required for Terraform install)
  become: true
  package:
    name: unzip
    state: "{{ packages_state }}"

- name: Install Terraform
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ teraform_tf_version }}/terraform_{{ teraform_tf_version }}_linux_amd64.zip"
    dest: "{{ teraform_tf_install_path }}"
    remote_src: true
  notify: update_aliases

- name: Add Terraform install directory to PATH
  become: true
  lineinfile:
    dest: /etc/environment
    backrefs: true
    regexp: 'PATH=(["]*)((?!.*?{{ terraform_tf_install_path }}).*?)(["]*)$'
    line: 'PATH=\1\2:{{ terraform_tf_install_path }}\3'

- name: Install Terragrunt
  become: true
  get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terraform_tg_version }}/terragrunt_linux_amd64"
    dest: "{{ terraform_tg_install_path }}terragrunt"
    mode: u+x,g+x,o+x
    force: true  # force update when newer version
  notify: update_aliases

- name: Set fact for bash aliases handler
  set_fact:
    tf_aliases: true
