---
- name: Install unzip (required for Terraform install)
  become: true
  package:
    name: unzip
    state: "{{ packages_state }}"

- name: Install Terraform 
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ tf_version }}/terraform_{{ tf_version }}_linux_amd64.zip"
    dest: "{{ tf_install_path }}"
    remote_src: True
  notify: update_aliases

- name: Add Terraform install directory to PATH
  become: true
  lineinfile:
    dest: /etc/environment
    backrefs: yes
    regexp: 'PATH=(["]*)((?!.*?{{ tf_install_path }}).*?)(["]*)$'
    line: 'PATH=\1\2:{{ tf_install_path }}\3'

- name: Install Terragrunt
  become: true
  get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ tg_version }}/terragrunt_linux_amd64"
    dest: "{{ tg_install_path }}terragrunt"
    mode: u+x,g+x,o+x
    force: true     # force update when newer version
  notify: update_aliases

- name: Set fact for bash aliases handler 
  set_fact:
    tf_aliases: true