---
- name: Install Terraform 
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ tf_version }}/terraform_{{ tf_version }}_linux_amd64.zip"
    dest: "{{ tf_install_path }}"
    remote_src: True

- name: Add Terraform install directory to PATH
  become: true
  lineinfile:
    dest: /etc/environment
    backrefs: yes
    regexp: 'PATH=(["]*)((?!.*?{{ tf_install_path }}).*?)(["]*)$'
    line: 'PATH=\1\2:{{ tf_install_path }}\3'

- name: Install terragrunt
  become: true
  get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ tg_version }}/terragrunt_linux_amd64"
    dest: "{{ tg_install_path }}terragrunt"
    mode: u+x,g+x,o+x