---
- name: Ensure dependencies are installed
  become: true
  apt:
    name: "{{ item }}"
    state: "{{ packages_state }}"
  loop:
    - ca-certificates
    - curl
    - gnupg

- name: Get Docker GPG key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present