- name: "[DEBUG] Print distro-related info"
  debug:
    msg: |
      OS family: {{ ansible_os_family }}
      Package manager: {{ ansible_pkg_mgr }}
      OS distro: {{ ansible_distribution }}
      OS releast name: {{ ansible_distribution_release }}

# Include distro-specific config (repository setup)
- name: "[yum] Install Docker prerequisites"
  include_tasks: docker-yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: "[apt] Install Docker prerequisites"
  include_tasks: docker-apt.yml
  when: ansible_pkg_mgr == 'apt'
  
- name: "[rpm] Install Docker prerequisites"
  include_tasks: docker-rpm.yml
  when: ansible_pkg_mgr == 'rpm'

# Install Docker once requirements are met
- name: Install Docker packages
  become: true
  package:
    name: "{{ item }}"
    state: "{{ packages_state }}"
  loop: 
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin
    - docker-compose-plugin
  notify: restart_docker

- name: Create Docker group
  group:
    name: docker
    state: present
  notify: restart_docker

- name: Add user to Docker group
  user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - docker
  notify: restart_docker