- name: "[DEBUG] Print distro-related info"
  debug:
    msg:
      - "OS family: {{ ansible_os_family }}"
      - "Package manager: {{ ansible_pkg_mgr }}"
      - "OS distro: {{ ansible_distribution }}"
      - "OS releast name: {{ ansible_distribution_release }}"

# Docker cannot be installed directly on WSL, skip install if WSL
- name: Check if running WSL
  command:
    cmd: grep WSL /proc/version
  register: wsl_grep
  # grep returns 2 if an error has occurred, 1 if no match, 0 if a match was found
  failed_when: wsl_grep.rc == 2
  changed_when: false

- name: Install Docker if not on WSL
  include_tasks: docker-main.yml
  when: wsl_grep.rc == 1      # no match for grep WSL 

- name: Skip install on WSL
  debug: 
    msg: WSL detected, skipping Docker install.
  when: wsl_grep.rc == 0      # match for grep WSL found