---
# ---------------- Bash aliases
- name: Ensure bashrc and bash_aliases exists
  file:
    path: "/home/{{ ansible_user_id }}/{{ item }}"
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: 0600
  loop:
    - .bashrc
    - .bash_aliases
  tags:
    - aliases

- name: Include bash aliases in bashrc
  blockinfile:
    marker_begin: "BASH ALIASES - BEGIN"
    marker_end: "BASH ALIASES - END"
    block: |
      if [ -f ~/.bash_aliases ]; then
          . ~/.bash_aliases
      fi
    path: "/home/{{ ansible_user_id }}/.bashrc"
  tags:
    - aliases

- name: Add bash aliases
  blockinfile:
    marker_begin: "BASE BASH ALIASES - BEGIN"
    marker_end: "BASE BASH ALIASES - END"
    block: "{{ lookup('template', '.bash_aliases.j2') }}"
    dest: "/home/{{ ansible_user_id }}/.bash_aliases"
  tags:
    - aliases