---
- name: Install vim
  become: true
  package:
    name: vim
    state: "{{ packages_state }}"

- name: Install tmux
  become: true
  package:
    name: tmux
    state: "{{ packages_state }}"

# - debug: var=ansible_user_id

- name: Add home directory config files
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user_id }}/{{ item }}"
  loop: 
    - .vimrc
    - .tmux.conf

- name: Install tree
  become: true
  package:
    name: tree
    state: "{{ packages_state }}"

- name: Add bash aliases
  import_tasks: bash_aliases.yml
  tags:
    - aliases