# --- Update package repositories for the system's package manager
- name: "[apt] Update package repository"
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
  when: ansible_pkg_mgr == "apt"

- name: "[yum] Update package repository"
  become: true
  yum:
    list: updates
    update_cache: true
  when: ansible_pkg_mgr == "yum"

# --- Install packages
- name: Install useful packages
  become: true
  package:
    name: vim
    state: "{{ packages_state }}"
  loop:
    - vim
    - tmux
    - jq
    - ripgrep

# --- Add config files
- name: Add home directory config files
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user_id }}/{{ item }}"
    mode: 0644
  loop:
    - .vimrc
    - .tmux.conf

- name: Install tree
  become: true
  package:
    name: tree
    state: "{{ packages_state }}"

- name: Add bash aliases
  import_tasks: bash_aliases.yml
  tags:
    - aliases

- name: Set visual & editor to vim
  blockinfile:
    marker_begin: "EXPORTS - BEGIN"
    marker_end: "EXPORTS - END"
    path: "/home/{{ ansible_user_id }}/.bashrc"
    block: |
      export VISUAL="vim"
      export EDITOR="$VISUAL"
