# find all possible versions at: https://releases.hashicorp.com/terraform/index.json
# TODO: automatically fetch latest version
terraform_tf_version: 1.5.5
terraform_tg_version: 0.49.1

# default path
terraform_tf_install_path: /usr/local/bin/
terraform_tg_install_path: /usr/local/bin/
